services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb
      ACCESS_TOKEN_SECRET: supersecret
      REFRESH_TOKEN_SECRET: supersecret2
      PORT: 3000

  frontend:
    build: ./frontend
    container_name: react_frontend #YH Note we dont need restart yet as if client fails I want to know why
    ports:
    - "5173:5173"
    depends_on:
      - backend
    environment:
      SERVER_URL: http://backend:3000

volumes:
  pgdata: