services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb
      ACCESS_TOKEN_SECRET: supersecret
      REFRESH_TOKEN_SECRET: supersecret2
      PORT: 3000

volumes:
  pgdata: